"""initial_migration

Revision ID: 3ef69d678b68
Revises: 
Create Date: 2025-10-06 13:05:24.275102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef69d678b68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Asistencia', schema=None) as batch_op:
        batch_op.alter_column('id_asistencia',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('hora_entrada',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('hora_salida',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_Asistencia_id_cliente'), ['id_cliente'], unique=False)

    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('numero_documento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('apellido_paterno',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('apellido_materno',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('Membresias', schema=None) as batch_op:
        batch_op.alter_column('id_membresia',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_membresia', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_inicio_membresia', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin_membresia', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('monto_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('monto_pagado', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('monto_pendiente', sa.Float(), nullable=False))
        batch_op.alter_column('id_pago',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha_pago',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('comprobante',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_Pagos_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_foreign_key(None, 'Membresias', ['id_membresia'], ['id_membresia'])
        batch_op.drop_column('monto')

    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('correo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.REAL(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Pagos_id_cliente'))
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('comprobante',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('fecha_pago',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_pago',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('monto_pendiente')
        batch_op.drop_column('monto_pagado')
        batch_op.drop_column('monto_total')
        batch_op.drop_column('fecha_fin_membresia')
        batch_op.drop_column('fecha_inicio_membresia')
        batch_op.drop_column('id_membresia')

    with op.batch_alter_table('Membresias', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_membresia',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Clientes', schema=None) as batch_op:
        batch_op.alter_column('fecha_registro',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('apellido_materno',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('apellido_paterno',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('numero_documento',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Asistencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Asistencia_id_cliente'))
        batch_op.alter_column('hora_salida',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hora_entrada',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_asistencia',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
